POST http://localhost:3001/api/notes 
Content-Type: application/json

{
  "content": "Esto es una nueva nota",
  "important": false,
  "userId": "6389845e092714a35fc80a70"
}

###

POST http://localhost:3001/api/notes 
Content-Type: application/json
